name: 'Setup Documentation Tools'
description: 'Setup Python and uv for documentation generation'
runs:
  using: 'composite'
  steps:
    - uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
