name: 'Setup Terraform'
description: 'Setup Terraform and related tools'
runs:
  using: 'composite'
  steps:
    - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
      with:
        terraform_wrapper: false
    - name: Install tflint
      shell: bash
      run: |
        curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
