name: Apply Tests

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
      - '**.tftest.hcl'
  pull_request:
    paths:
      - '**.tf'
      - '**.tftest.hcl'
  workflow_dispatch:
    inputs:
      run_full_suite:
        description: 'Run full test suite (all apply tests)'
        required: false
        type: boolean
        default: false

env:
  MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGODB_ATLAS_ORG_ID }}
  MONGODB_ATLAS_CLIENT_ID: ${{ secrets.MONGODB_ATLAS_CLIENT_ID }}
  MONGODB_ATLAS_CLIENT_SECRET: ${{ secrets.MONGODB_ATLAS_CLIENT_SECRET }}
  MONGODB_ATLAS_BASE_URL: ${{ secrets.MONGODB_ATLAS_BASE_URL }}

jobs:
  dev-cluster-test:
    name: Dev Cluster Test
    if: ${{ !inputs.run_full_suite }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd  # v3.1.2
        with:
          terraform_wrapper: false
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6  # v2.0.0
        with:
          just-version: '1.40.0'

      - name: Run Dev Cluster Test
        run: |
          terraform init
          terraform test -filter=tests/apply_dev_cluster.tftest.hcl -var "org_id=${MONGODB_ATLAS_ORG_ID}"

  full-test-suite:
    name: Full Test Suite
    if: ${{ inputs.run_full_suite }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8
        with:
          terraform_wrapper: false
      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff
        with:
          just-version: '1.40.0'

      - name: Run Full Test Suite
        run: just integration-tests
