name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          fetch-depth: 0  # Fetch all history for git operations
      
      - uses: ./.github/actions/setup-base
      
      - uses: ./.github/actions/setup-terraform
      
      - uses: ./.github/actions/setup-docs
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Create release branch and prepare release
        run: |
          just release-commit ${{ inputs.version }}
      
      - name: Push release branch and tag
        run: |
          git push origin ${{ inputs.version }}
          git push origin ${{ inputs.version }} --tags
          
          echo "✓ Release ${{ inputs.version }} pushed successfully"
          echo "  Branch: https://github.com/${{ github.repository }}/tree/${{ inputs.version }}"
          echo "  Tag: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.version }}"
      
      - name: Compute Terraform Registry source
        id: registry
        run: |
          REGISTRY_SOURCE=$(just tf-registry-source)
          echo "registry_source=${REGISTRY_SOURCE}" >> $GITHUB_OUTPUT
          echo "Terraform Registry source: ${REGISTRY_SOURCE}"
      
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.version }}
          name: Release ${{ inputs.version }}
          body: |
            ## Release ${{ inputs.version }}
            
            This release includes version-specific documentation with absolute links.
            
            ### Installation
            
            ```hcl
            module "cluster" {
              source  = "${{ steps.registry.outputs.registry_source }}"
              version = "${{ inputs.version }}"
              
              # Your configuration here
              project_id   = "your-project-id"
              name         = "my-cluster"
              cluster_type = "SHARDED"
              # ... additional configuration
            }
            ```
            
            ### Documentation
            
            - [README](https://github.com/${{ github.repository }}/blob/${{ inputs.version }}/README.md)
            - [Examples](https://github.com/${{ github.repository }}/blob/${{ inputs.version }}/examples/)
            - [Contributing Guide](https://github.com/${{ github.repository }}/blob/${{ inputs.version }}/CONTRIBUTING.md)
            
            ### Changes
            
            See the commit history for details on what changed in this release.
          draft: false
          prerelease: false
          generate_release_notes: true
